name: Upload Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ Richiesto per OIDC

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      - name: Clean dist/
        run: rm -rf dist/*
      
      - name: Build package
        run: python -m build

      - name: List built files
        run: ls -lh dist/

      - name: Publish to PyPI with Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
